title: "sine"
description: information security notes
author: sine
google_analytics:

permalink: "/:year/:month/:title"

paginate: 50
paginate_path: "/:num"

gems: 
  - jekyll-paginate

sass:
  style: compressed

google_analytics: UA-64260520-1
twitter: 73696e65
github: 73696e65

# Tipue search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]
